In [338]:
# importing dependencies 
import pandas as pd

In [347]:
# Cleaning national shark data
sharkAttacks = pd.read_csv('data/attacks.csv', encoding='cp1252').drop(columns=['Unnamed: 22', 'Unnamed: 23'])
sharkAttacks.drop(columns=['Time'])
sharkAttacks.dropna()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,...,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0
8,2018.05.26.b,26-May-2018,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,...,N,17h00,"Bull shark, 6'","K.McMurray, TrackingSharks.com",2018.05.26.b-High.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.b,2018.05.26.b,6295.0
10,2018.05.24,24-May-2018,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,...,N,Morning,Grey reef shark,"ABC.net.au ,05/24/2018",2018.05.24-CairnsAquarium.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.24,2018.05.24,6293.0
13,2018.05.13.a,13-May-2018,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,...,N,08h15,Invalid incident,"K. McMurray, TrackingSharks.com",2018.05.13.a-Berryman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.13.a,2018.05.13.a,6290.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5814,1880.11.25,25-Nov-1880,1880.0,Unprovoked,AUSTRALIA,Queensland,"Petrie Bight, Brisbane River",Swimming,Alexey Drury,M,...,Y,Afternoon,Bull shark,"Bucks County Gazette, 2/10/1881, Sunday Mail (...",1880.11.25-AlexeyDrury.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1880.11.25,1880.11.25,489.0
5922,1868.05.13,13-May-1868,1868.0,Unprovoked,INDIA,Hoogly River,Ghat,Standing,male,M,...,Y,Before 10h30,Identified as C. gangeticus by Dr. J. Fayrer,"J. Fayrer, M.D.",1868.05.13-Hindoo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1868.05.13,1868.05.13,381.0
6242,ND.0064,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Swimming naked near a date palm where many dat...,male,M,...,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0064-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0064,ND.0064,61.0
6243,ND.0063,1960s,0.0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River near Abu al Khasib,Swimming in section of river used for washing ...,male,M,...,N,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0063-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0063,ND.0063,60.0
6265,ND.0038,1941-1942,0.0,Unprovoked,IRAQ,Basrah,Shatt-el Arab River near a small boat stand,Swimming,male,M,...,Y,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0038-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0038,ND.0038,38.0

In [348]:
sharkAttacks['Country'].unique()

array(['USA', 'AUSTRALIA', 'MEXICO', 'BRAZIL', 'ENGLAND', 'SOUTH AFRICA',
       'THAILAND', 'COSTA RICA', 'MALDIVES', 'BAHAMAS', 'NEW CALEDONIA',
       'ECUADOR', 'MALAYSIA', 'LIBYA', nan, 'CUBA', 'MAURITIUS',
       'NEW ZEALAND', 'SPAIN', 'SAMOA', 'SOLOMON ISLANDS', 'JAPAN',
       'EGYPT', 'ST HELENA, British overseas territory', 'COMOROS',
       'REUNION', 'FRENCH POLYNESIA', 'UNITED KINGDOM',
       'UNITED ARAB EMIRATES', 'PHILIPPINES', 'INDONESIA', 'CHINA',
       'COLUMBIA', 'CAPE VERDE', 'Fiji', 'DOMINICAN REPUBLIC',
       'CAYMAN ISLANDS', 'ARUBA', 'MOZAMBIQUE', 'FIJI', 'PUERTO RICO',
       'ITALY', 'ATLANTIC OCEAN', 'GREECE', 'ST. MARTIN', 'FRANCE',
       'PAPUA NEW GUINEA', 'TRINIDAD & TOBAGO', 'KIRIBATI', 'ISRAEL',
       'DIEGO GARCIA', 'TAIWAN', 'JAMAICA', 'PALESTINIAN TERRITORIES',
       'GUAM', 'SEYCHELLES', 'BELIZE', 'NIGERIA', 'TONGA', 'SCOTLAND',
       'CANADA', 'CROATIA', 'SAUDI ARABIA', 'CHILE', 'ANTIGUA', 'KENYA',
       'RUSSIA', 'TURKS & CAICOS', 'UNITED ARAB EMIRATES (UAE)', 'AZORES',
       'SOUTH KOREA', 'MALTA', 'VIETNAM', 'MADAGASCAR', 'PANAMA',
       'SOMALIA', 'NEVIS', 'BRITISH VIRGIN ISLANDS', 'NORWAY', 'SENEGAL',
       'YEMEN', 'GULF OF ADEN', 'Sierra Leone', 'ST. MAARTIN',
       'GRAND CAYMAN', 'Seychelles', 'LIBERIA', 'VANUATU', 'MEXICO ',
       'HONDURAS', 'VENEZUELA', 'SRI LANKA', ' TONGA', 'URUGUAY', 'INDIA',
       'MICRONESIA', 'CARIBBEAN SEA', 'OKINAWA', 'TANZANIA',
       'MARSHALL ISLANDS', 'EGYPT / ISRAEL', 'NORTHERN ARABIAN SEA',
       'HONG KONG', 'EL SALVADOR', 'ANGOLA', 'BERMUDA', 'MONTENEGRO',
       'IRAN', 'TUNISIA', 'NAMIBIA', 'NORTH ATLANTIC OCEAN', 'PORTUGAL',
       'SOUTH CHINA SEA', 'BANGLADESH', 'PALAU', 'WESTERN SAMOA',
       'PACIFIC OCEAN ', 'BRITISH ISLES', 'GRENADA', 'IRAQ', 'TURKEY',
       'SINGAPORE', 'NEW BRITAIN', 'SUDAN', 'JOHNSTON ISLAND',
       'SOUTH PACIFIC OCEAN', 'NEW GUINEA', 'RED SEA',
       'NORTH PACIFIC OCEAN', 'FEDERATED STATES OF MICRONESIA',
       'MID ATLANTIC OCEAN', 'ADMIRALTY ISLANDS', 'BRITISH WEST INDIES',
       'SOUTH ATLANTIC OCEAN', 'PERSIAN GULF', 'RED SEA / INDIAN OCEAN',
       'PACIFIC OCEAN', 'NORTH SEA', 'NICARAGUA ', 'MALDIVE ISLANDS',
       'AMERICAN SAMOA', 'ANDAMAN / NICOBAR ISLANDAS', 'GABON', 'MAYOTTE',
       'NORTH ATLANTIC OCEAN ', 'THE BALKANS', 'SUDAN?', 'ARGENTINA',
       'MARTINIQUE', 'INDIAN OCEAN', 'GUATEMALA', 'NETHERLANDS ANTILLES',
       'NORTHERN MARIANA ISLANDS', 'IRAN / IRAQ', 'JAVA', 'SIERRA LEONE',
       ' PHILIPPINES', 'NICARAGUA', 'CENTRAL PACIFIC',
       'SOLOMON ISLANDS / VANUATU', 'SOUTHWEST PACIFIC OCEAN',
       'BAY OF BENGAL', 'MID-PACIFC OCEAN', 'SLOVENIA', 'CURACAO',
       'ICELAND', 'ITALY / CROATIA', 'BARBADOS', 'MONACO', 'GUYANA',
       'HAITI', 'SAN DOMINGO', 'IRELAND', 'KUWAIT', 'YEMEN ',
       'REUNION ISLAND', 'FALKLAND ISLANDS', 'CRETE', 'CYPRUS', 'EGYPT ',
       'WEST INDIES', 'BURMA', 'LEBANON', 'PARAGUAY',
       'BRITISH NEW GUINEA', 'CEYLON', 'OCEAN', 'GEORGIA', 'SYRIA',
       'TUVALU', 'INDIAN OCEAN?', 'GUINEA', 'ANDAMAN ISLANDS',
       'EQUATORIAL GUINEA / CAMEROON', 'COOK ISLANDS', 'TOBAGO', 'PERU',
       'AFRICA', 'ALGERIA', 'Coast of AFRICA', 'TASMAN SEA', 'GHANA',
       'GREENLAND', 'MEDITERRANEAN SEA', 'SWEDEN', 'ROATAN',
       'Between PORTUGAL & INDIA', 'DJIBOUTI', 'BAHREIN', 'KOREA',
       'RED SEA?', 'ASIA?', 'CEYLON (SRI LANKA)'], dtype=object)

In [350]:
# reading in csv for USA state lat and long
lat_long = pd.read_csv('data/Lat_long_states.csv')
lat_long

   State        Lat        Long
0     WI  44.500000  -89.500000
1     WV  39.000000  -80.500000
2     VT  44.000000  -72.699997
3     TX  31.000000 -100.000000
4     SD  44.500000 -100.000000
5     RI  41.700001  -71.500000
6     OR  44.000000 -120.500000
7     NY  43.000000  -75.000000
8     NH  44.000000  -71.500000
9     NE  41.500000 -100.000000
10    KS  38.500000  -98.000000
11    MS  33.000000  -90.000000
12    IL  40.000000  -89.000000
13    DE  39.000000  -75.500000
14    CT  41.599998  -72.699997
15    AR  34.799999  -92.199997
16    IN  40.273502  -86.126976
17    MO  38.573936  -92.603760
18    FL  27.994402  -81.760254
19    NV  39.876019 -117.224121
20    ME  45.367584  -68.972168
21    MI  44.182205  -84.506836
22    GA  33.247875  -83.441162
23    HI  19.741755 -155.844437
24    AK  66.160507 -153.369141
25    TN  35.860119  -86.660156
26    VA  37.926868  -78.024902
27    NJ  39.833851  -74.871826
28    KY  37.839333  -84.270020
29    ND  47.650589 -100.437012
30    MN  46.392410  -94.636230
31    OK  36.084621  -96.921387
32    MT  46.965260 -109.533691
33    WA  47.751076 -120.740135
34    UT  39.419220 -111.950684
35    CO  39.113014 -105.358887
36    OH  40.367474  -82.996216
37    AL  32.318230  -86.902298
38    IA  42.032974  -93.581543
39    NM  34.307144 -106.018066
40    SC  33.836082  -81.163727
41    PA  41.203323  -77.194527
42    AZ  34.048927 -111.093735
43    MD  39.045753  -76.641273
44    MA  42.407211  -71.382439
45    CA  36.778259 -119.417931
46    ID  44.068203 -114.742043
47    WY  43.075970 -107.290283
48    NC  35.782169  -80.793457
49    LA  30.391830  -92.329100

In [351]:
# Creating dict of state names and abbriviations 
us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'American Samoa': 'AS',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District of Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Guam': 'GU',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Northern Mariana Islands':'MP',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virgin Islands': 'VI',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
}

In [352]:
# Writting dict to dataframe 
us_state_abbrev_df = pd.DataFrame.from_dict(us_state_abbrev, orient='index')

indexed = us_state_abbrev_df.reset_index()

indexed.columns = ['Area','State']
indexed

                        Area State
0                    Alabama    AL
1                     Alaska    AK
2             American Samoa    AS
3                    Arizona    AZ
4                   Arkansas    AR
5                 California    CA
6                   Colorado    CO
7                Connecticut    CT
8                   Delaware    DE
9       District of Columbia    DC
10                   Florida    FL
11                   Georgia    GA
12                      Guam    GU
13                    Hawaii    HI
14                     Idaho    ID
15                  Illinois    IL
16                   Indiana    IN
17                      Iowa    IA
18                    Kansas    KS
19                  Kentucky    KY
20                 Louisiana    LA
21                     Maine    ME
22                  Maryland    MD
23             Massachusetts    MA
24                  Michigan    MI
25                 Minnesota    MN
26               Mississippi    MS
27                  Missouri    MO
28                   Montana    MT
29                  Nebraska    NE
30                    Nevada    NV
31             New Hampshire    NH
32                New Jersey    NJ
33                New Mexico    NM
34                  New York    NY
35            North Carolina    NC
36              North Dakota    ND
37  Northern Mariana Islands    MP
38                      Ohio    OH
39                  Oklahoma    OK
40                    Oregon    OR
41              Pennsylvania    PA
42               Puerto Rico    PR
43              Rhode Island    RI
44            South Carolina    SC
45              South Dakota    SD
46                 Tennessee    TN
47                     Texas    TX
48                      Utah    UT
49                   Vermont    VT
50            Virgin Islands    VI
51                  Virginia    VA
52                Washington    WA
53             West Virginia    WV
54                 Wisconsin    WI
55                   Wyoming    WY

In [344]:
# merging state and lat long into one dataframe 
indexed.merge(lat_long, left_on='State', right_on='State')

              Area State        Lat        Long
0          Alabama    AL  32.318230  -86.902298
1           Alaska    AK  66.160507 -153.369141
2          Arizona    AZ  34.048927 -111.093735
3         Arkansas    AR  34.799999  -92.199997
4       California    CA  36.778259 -119.417931
5         Colorado    CO  39.113014 -105.358887
6      Connecticut    CT  41.599998  -72.699997
7         Delaware    DE  39.000000  -75.500000
8          Florida    FL  27.994402  -81.760254
9          Georgia    GA  33.247875  -83.441162
10          Hawaii    HI  19.741755 -155.844437
11           Idaho    ID  44.068203 -114.742043
12        Illinois    IL  40.000000  -89.000000
13         Indiana    IN  40.273502  -86.126976
14            Iowa    IA  42.032974  -93.581543
15          Kansas    KS  38.500000  -98.000000
16        Kentucky    KY  37.839333  -84.270020
17       Louisiana    LA  30.391830  -92.329100
18           Maine    ME  45.367584  -68.972168
19        Maryland    MD  39.045753  -76.641273
20   Massachusetts    MA  42.407211  -71.382439
21        Michigan    MI  44.182205  -84.506836
22       Minnesota    MN  46.392410  -94.636230
23     Mississippi    MS  33.000000  -90.000000
24        Missouri    MO  38.573936  -92.603760
25         Montana    MT  46.965260 -109.533691
26        Nebraska    NE  41.500000 -100.000000
27          Nevada    NV  39.876019 -117.224121
28   New Hampshire    NH  44.000000  -71.500000
29      New Jersey    NJ  39.833851  -74.871826
30      New Mexico    NM  34.307144 -106.018066
31        New York    NY  43.000000  -75.000000
32  North Carolina    NC  35.782169  -80.793457
33    North Dakota    ND  47.650589 -100.437012
34            Ohio    OH  40.367474  -82.996216
35        Oklahoma    OK  36.084621  -96.921387
36          Oregon    OR  44.000000 -120.500000
37    Pennsylvania    PA  41.203323  -77.194527
38    Rhode Island    RI  41.700001  -71.500000
39  South Carolina    SC  33.836082  -81.163727
40    South Dakota    SD  44.500000 -100.000000
41       Tennessee    TN  35.860119  -86.660156
42           Texas    TX  31.000000 -100.000000
43            Utah    UT  39.419220 -111.950684
44         Vermont    VT  44.000000  -72.699997
45        Virginia    VA  37.926868  -78.024902
46      Washington    WA  47.751076 -120.740135
47   West Virginia    WV  39.000000  -80.500000
48       Wisconsin    WI  44.500000  -89.500000
49         Wyoming    WY  43.075970 -107.290283

In [414]:
sharkAttacks.loc[sharkAttacks['Country'] == 'AUSTRALIA']

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0
5,2018.06.03.b,03-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Flat Rock, Ballina",Kite surfing,Chris …,M,...,N,NaN,NaN,"Daily Telegraph, 6/4/2018",2018.06.03.b-FlatRock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.b,2018.06.03.b,6298.0
10,2018.05.24,24-May-2018,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,...,N,Morning,Grey reef shark,"ABC.net.au ,05/24/2018",2018.05.24-CairnsAquarium.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.24,2018.05.24,6293.0
14,2018.05.00,May 2018,2018.0,Provoked,AUSTRALIA,Westerm Australia,Dugong Bay,Feeding sharks,Melisa Brunning,F,...,N,NaN,"Tawny nurse shark, 2m","Perth Now, 6/30/2018",2018.05.00-Brunning.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.00,2018.05.00,6289.0
16,2018.05.09,09-May-2018,2018.0,Questionable,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",Surfing,male,M,...,N,10h30,Shark involvement not confirmed,"B. Myatt, GSAF",2018.05.09-SharpesBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.09,2018.05.09,6287.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6294,ND.0008,Before 1906,0.0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,...,Y,NaN,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0008-Fisherman2-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0008,ND.0008,9.0
6295,ND.0007,Before 1906,0.0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,...,Y,NaN,Blue pointers,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0007 - Fisherman-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0007,ND.0007,8.0
6296,ND.0006,Before 1906,0.0,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,M,...,Y,NaN,Said to involve a grey nurse shark that leapt ...,"L. Becke in New York Sun, 9/9/1906; L. Schultz...",ND-0006-ArabBoy-Prymount.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0006,ND.0006,7.0
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0

In [303]:
# printing areas in south africa 
sharkAttacks_cleaned.loc[sharkAttacks['Country'] == 'AUSTRALIA'].Area.unique()

array(['Queensland', 'Western Australia', 'Victoria', 'New South Wales',
       'South Australia', 'Tasmania', 'Northern Territory',
       'Territory of Cocos (Keeling) Islands', 'Victoria ',
       'Torres Strait', 'Queensland '], dtype=object)

In [415]:
# replacing area names for continuity 
sharkAttacks_replace =sharkAttacks.replace(['Victoria '], 'Victoria')

In [355]:
# Creating dataframe with Australian areas and long lat 
Aus_shark = {'Area': ['Victoria', 
          'Northern Territory',
          'South Australia',
          'Western Australia',
          'Queensland', 
          'New South Wales',
        'Tasmania',
        'Territory of Cocos (Keeling) Islands',
        'Torres Strait',
        'Queensland'], 
 'Lat': [-37.020100, 
         -19.491411, 
         -30.000233, 
         -25.042261, 
         -20.917574, 
         -31.840233,
        -41.640079,
        -12.164165,
        -10.181578,
        -20.917574], 
    'Long': [144.964600, 
             132.550964, 
             136.209152, 
             117.793221, 
             142.702789, 
             145.612793,
            146.315918,
            96.870956,
            142.26641,
            142.702789]}

In [356]:
Aus_shark_df = pd.DataFrame(data=Aus_shark)
Aus_shark_df

                                   Area        Lat        Long
0                              Victoria -37.020100  144.964600
1                    Northern Territory -19.491411  132.550964
2                       South Australia -30.000233  136.209152
3                     Western Australia -25.042261  117.793221
4                            Queensland -20.917574  142.702789
5                       New South Wales -31.840233  145.612793
6                              Tasmania -41.640079  146.315918
7  Territory of Cocos (Keeling) Islands -12.164165   96.870956
8                         Torres Strait -10.181578  142.266410
9                            Queensland -20.917574  142.702789

In [357]:
# printing areas in south africa 
sharkAttacks_cleaned.loc[sharkAttacks['Country'] == 'SOUTH AFRICA'].Area.unique()

array(['Western Cape Province', 'Eastern Cape Province', 'KwaZulu-Natal',
       'Western Province',
       'KwaZulu-Natal between Port Edward and Port St Johns'],
      dtype=object)

In [358]:
# South africa shark data 
SA_sharkAttacks =sharkAttacks_cleaned.loc[sharkAttacks['Country'] == 'SOUTH AFRICA']

In [359]:
# replacing area names for continuity 
Cleaned_SA_sharkAttacks=SA_sharkAttacks.replace(['KwaZulu-Natal between Port Edward and Port St Johns'], 'KwaZulu-Natal')

In [360]:
# Replacing area names for continuity
Cleaned_SA_sharkAttacks.replace(['Western Province'], 'Western Cape Province').Area.unique()

array(['Western Cape Province', 'Eastern Cape Province', 'KwaZulu-Natal'],
      dtype=object)

In [361]:
# Creating dict with south africa areas 
SA_shark = {'Area': 
            ['KwaZulu-Natal', 
             'Western Cape Province', 
             'Eastern Cape Province'], 
            'Lat': [-29.883333,
                    -33.918861, 
                    -30.362110], 
            'Long': [31.049999, 
                     18.423300, 
                     28.801413]}

In [362]:
# Creating dataframe with lat and long for south africa data 
SA_shark_df = pd.DataFrame(data=SA_shark)
SA_shark_df

                    Area        Lat       Long
0          KwaZulu-Natal -29.883333  31.049999
1  Western Cape Province -33.918861  18.423300
2  Eastern Cape Province -30.362110  28.801413

In [363]:
# Filtering based on country and checking for unique values in the area column
MEX_data = sharkAttacks_cleaned.loc[sharkAttacks['Country'] == 'MEXICO']
MEX_data.Area.unique()

array(['Quintana Roo', 'Sinaloa', 'Guerrero', 'Guerro', 'Baja California',
       'Veracruz'], dtype=object)

In [364]:
# Replacing area names for continuity
MEX_data.replace(['Guerro'], 'Guerrero').Area.unique()

array(['Quintana Roo', 'Sinaloa', 'Guerrero', 'Baja California',
       'Veracruz'], dtype=object)

In [365]:
# Creating dict with south africa areas 
MEX_shark = {'Area': 
            ['Quintana Roo', 
             'Sinaloa', 
             'Guerrero',
            'Baja California',
            'Veracruz'], 
            'Lat': [19.263021,
                    25.790466, 
                    18.020529,
                    32.522499,
                    19.173773], 
            'Long': [-87.450912, 
                    -108.985886, 
                     -99.662476,
                     -117.046623,
                     -96.134224]}

In [366]:
# Creating dataframe with lat and long for south africa data 
MEX_shark_df = pd.DataFrame(data=MEX_shark)
MEX_shark_df

              Area        Lat        Long
0     Quintana Roo  19.263021  -87.450912
1          Sinaloa  25.790466 -108.985886
2         Guerrero  18.020529  -99.662476
3  Baja California  32.522499 -117.046623
4         Veracruz  19.173773  -96.134224

In [373]:
# printing areas in BRAZIL
sharkAttacks_cleaned.loc[sharkAttacks['Country'] == 'BRAZIL'].Area.unique()

array(['Pernambuco', 'Fernando de Noronha', 'Rio de Janeiro'],
      dtype=object)

In [374]:
# Creating dict with south africa areas 
BZ_shark = {'Area': 
            ['Pernambuco', 
             'Fernando de Noronha', 
             'Rio de Janeiro'], 
            'Lat': [-8.472372,
                    -3.853808,
                     -22.908333], 
            'Long': [-37.946777, 
                    -32.423786, 
                     -43.196388]}

In [375]:
# Creating dataframe with lat and long for BRAZIL data 
BZ_shark_df = pd.DataFrame(data=BZ_shark)
BZ_shark_df

                  Area        Lat       Long
0           Pernambuco  -8.472372 -37.946777
1  Fernando de Noronha  -3.853808 -32.423786
2       Rio de Janeiro -22.908333 -43.196388

In [416]:
ENG_data = sharkAttacks.loc[sharkAttacks['Country'] == 'ENGLAND']
ENG_data

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
13,2018.05.13.a,13-May-2018,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,...,N,08h15,Invalid incident,"K. McMurray, TrackingSharks.com",2018.05.13.a-Berryman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.13.a,2018.05.13.a,6290.0
1213,2008.08.30.a,30-Aug-2008,2008.0,Provoked,ENGLAND,North Devon,Lundy Island,Fishing,Stephen Perkins,M,...,N,NaN,Blue shark,"Telegraph.co.uk, 9/1/2008",2008.08.30.a-Perkins.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.08.30.a,2008.08.30.a,5090.0
1376,2007.05.17.R,Reported 17-May-2007,2007.0,Provoked,ENGLAND,Kent,Folkestone,Fishing,Phil Tanner,M,...,N,Afternoon,"Lesser spotted dogfish, Scyliorhinus canicula,...","V. Wheeler, The Sun, 5/17/2007",2007.05.17.R-PhilTanner.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2007.05.17.R,2007.05.17.R,4927.0
2073,2000.02.14,14-Feb-2000,2000.0,Provoked,ENGLAND,Worcestershire,The Fountain Pub in Tenbury Wells,Feeding prawns to captive sharks,"Paul Smith, a chef",M,...,N,NaN,"Miami, a 60 cm blacktip shark and two 60 cm b...","The Sun (London), 2/17/2000",2000.02.14-Smith.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.02.14,2000.02.14,4230.0
3024,1981.06.15.R,Reported 15-Jun-1981,1981.0,Boat,ENGLAND,NaN,Isle of Wight,Fishing,2 fishermen,M,...,N,NaN,"13', 400-lb thresher shark","The Times (London), 6/15/1981",1981.06.15.R-Isle-of-Wight.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1981.06.15.R,1981.06.15.R,3279.0
3406,1970.01.09.R,Reported 09-Jan-1970,1970.0,Unprovoked,ENGLAND,Devon,Teignmouth,Attempted to return injured shark to the sea,a fisherman,M,...,N,NaN,8' blue shark,"Reading Eagle, 1/9/1970",1970.01.09.R-England.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1970.01.09.R,1970.01.09.R,2897.0
3426,1969.07.27,27-Jul-1969,1969.0,Provoked,ENGLAND,NaN,NaN,NaN,Eric Brown,M,...,N,NaN,NaN,H.D. Baldridge (1994) SAF Case #1611,1969.07.27-NV-Brown.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1969.07.27,1969.07.27,2877.0
3471,1968.06.00,Jun-1968,1968.0,Unprovoked,ENGLAND,NaN,NaN,NaN,Roy Cloke,M,...,N,NaN,Blue shark,"H.D. Baldridge (1994), SAF Case #1515",1968.06.00-NV-Cloke.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1968.06.00,1968.06.00,2832.0
3975,1960.08.04.b,04-Aug-1960,1960.0,Provoked,ENGLAND,In the English Channel,Off the south Devon coast,Helping angler land a shark,William Capel,M,...,N,NaN,80-lb hooked shark,"Newcastle Morning Herald (NSW, Australia), 8/6...",1960.08.04.b-Capel.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1960.08.04.b,1960.08.04.b,2328.0
5164,1925.09.03,03-Sep-1925,1925.0,Unprovoked,ENGLAND,Isle of Wight,Off Shanklin,Fishing,Mr. S. Page,M,...,N,08h00,NaN,C. Moore. GSAF,1925.09.03-Page-Isle-of-Wight.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1925.09.03,1925.09.03,1139.0
5180,1924.07.14,14-Jul-1924,1924.0,Provoked,ENGLAND,Dorset,Weymouth,Fishing for mackerel,2 fishermen,M,...,N,NaN,12' shark,"C. Moore, GSAF; The Times, 7/14/1924",1924.07.14-Weymouth.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1924.07.14,1924.07.14,1123.0
5220,1922.09.26.R,Reported 26-Sep-1922,1922.0,Unprovoked,ENGLAND,East Yorkshire,Hornsea,Swimming,Mr.P. H. Lee,M,...,Y,NaN,NaN,"Western Argus, 9/26/1922",1922.09.26.R-Lee.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1922.09.26.R,1922.09.26.R,1083.0
5242,1921.09.00,Sep-1921,1921.0,Provoked,ENGLAND,Dorset,Weymouth,Fishing,Roberts,M,...,N,NaN,"Blue shark, 4'","Argus, 10/8/1921",1921.09.00-Roberts.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1921.09.00,1921.09.00,1061.0
5448,1907.09.18.R,Reported 19-Sep-1907,1907.0,Invalid,ENGLAND,English Channel,NaN,Swimming,J. Wolffe,M,...,NaN,NaN,Questionable,"C. Moore, GSAF",1907.09.18.R-Wolffe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1907.09.18.R,1907.09.18.R,855.0
5870,1876.00.00.c,1876,1876.0,Unprovoked,ENGLAND,"Between Hastings & Fairlight, Sussex",NaN,NaN,male,M,...,N,NaN,Blue or porbeagle shark,MEDSAF,1876.00.00.c-MEDSAF.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1876.00.00.c,1876.00.00.c,433.0
5997,1856.06.21.R,Reported 21-Jun-1856,1856.0,Unprovoked,ENGLAND,Isle of Wight,Colwell Bay,Swimming,male,M,...,Y,NaN,NaN,"C. Moore, GSAF",1856.06.21.R-Isle-of-Wight.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1856.06.21.R,1856.06.21.R,306.0
6038,1848.07.00,Jul-1848,1848.0,Unprovoked,ENGLAND,Norfolk,Hunstanton,Standing,male,M,...,N,NaN,NaN,"C. Moore, citing R. Peirce",1848.07.00-Hunstanton.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1848.07.00,1848.07.00,265.0
6053,1845.09.16.R,Reported 16-Sep-1845,1845.0,Unprovoked,ENGLAND,NaN,NaN,NaN,a school teacher,M,...,N,NaN,NaN,C. Moore. GSAF,1845.09.16.R-England.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1845.09.16.R,1845.09.16.R,250.0
6079,1836.08.19.R,Reported 19-Aug-1836,NaN,Unprovoked,ENGLAND,Cumberland,Whitehaven,Swimming,a boy,M,...,Y,NaN,NaN,"C. Moore, GSAF",1835.08.19.R-Whitehaven.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1836.08.19.R,1836.08.19.R,224.0
6104,1826.08.15.R,Reported 15-Aug-1826,1826.0,Unprovoked,ENGLAND,Cumberland,Whitehaven,Bathing,child,NaN,...,NaN,NaN,NaN,"The Times (London), 8/15/1826",1826.08.15.R-Whitehaven.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1826.08.15.R,1826.08.15.R,199.0
6118,1812.07.00,May 1812,1812.0,Unprovoked,ENGLAND,Devon,Mill Bay,Swimming,soldier from the Lancashire militia,M,...,N,NaN,Thought to involve a porbeagle or mako shark,"C. Moore, GSAF",1812.07.00-Mill-Bay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1812.07.00,1812.07.00,185.0
6134,1792.09.12,12-Sep-1792,1792.0,Provoked,ENGLAND,NaN,On the Thames River,Fishing,male,M,...,Y,NaN,NaN,"The Waterford Herald, 9/15/1792",1792.09.12-Thames.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1792.09.12,1792.09.12,169.0
6139,1785.09.26.R,Reported 26-Sep-1785,1785.0,Unprovoked,ENGLAND,Sussex,Brighton,NaN,NaN,M,...,Y,NaN,Tiger shark?,"C. Moore, GSAF",1785.09.26.R-Brighton.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1785.09.26.R,1785.09.26.R,164.0

In [377]:
# Creating dict with ENGLAND areas 
ENG_shark = {'Area': 
            ['Cornwall', 
             'Kent'], 
            'Lat': [50.503632,
                    47.378010], 
            'Long': [-4.652498, 
                    -122.237381]}

In [378]:
# Creating dataframe with lat and long for BRAZIL data 
ENG_shark_df = pd.DataFrame(data=ENG_shark)
ENG_shark_df

       Area        Lat        Long
0  Cornwall  50.503632   -4.652498
1      Kent  47.378010 -122.237381

In [379]:
# printing areas in THAILAND
sharkAttacks_cleaned.loc[sharkAttacks['Country'] == 'THAILAND'].Area.unique()

array(['Phuket'], dtype=object)

In [388]:
sharks = {
    'Area':
    ['Phuket',
    'Cocos Island',
    'Alifu Alifu Atoll'],
    'Lat': [7.878978,
           5.528228,
           4.215128],
    'Long': [98.398392,
            -87.05743,
            72.864471]
}

In [389]:
# Creating dataframe with lat and long for THAILAND data 
shark_df = pd.DataFrame(data=sharks)
shark_df

                Area       Lat       Long
0             Phuket  7.878978  98.398392
1       Cocos Island  5.528228 -87.057430
2  Alifu Alifu Atoll  4.215128  72.864471

In [417]:
# printing areas in BAHAMAS
BAH_sharks = sharkAttacks.loc[sharkAttacks['Country'] == 'BAHAMAS']

In [397]:
# printing areas in THAILAND
BAH_sharks.loc[BAH_sharks['Country'] == 'BAHAMAS'].Area.unique()

array(['New Providence ', 'Abaco Islands', 'Exuma Islands', 'West End',
       'Northern Bahamas', 'Grand Bahama Island', 'Berry Islands',
       'Walkers Cay', 'Out Islands', 'Cat Cay', 'Cay Sal Bank',
       'Andros Islands'], dtype=object)

In [400]:
BAH_sharks.replace(['New Providence '], 'New Providence')

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
138,2017.06.02,02-Jun-2017,2017.0,Unprovoked,BAHAMAS,New Providence,Athol Island,Snorkeling,Tiffany Johnson,F,...,N,Shortly before 12h00,Tiger shark,"Tribune 242, 6/2/2017",2017.06.02-Johnson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.02,2017.06.02,6165.0
460,2015.01.06,06-Jan-2015,2015.0,Unprovoked,BAHAMAS,Abaco Islands,"Tahiti Beach, Elbow Cay",Snorkeling,Lacy Webb,F,...,N,16h00,White shark or oceanic whitetip shark,"Britt Martin; Local10, 1/7/2015",2015.01.06-Webb-Martin.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.01.06,2015.01.06,5843.0
646,2013.07.29.c,28-Jul-2013,2013.0,Unprovoked,BAHAMAS,Abaco Islands,Scotland Cay,Spearfishing,Erik Norrie,M,...,N,16h05,6' shark,"CBS Miami, 8/1/2013",2013.07.29.c-Norrie.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2013.07.29.c,2013.07.29.c,5657.0
649,2013.07.28.b,28-Jul-2013,2013.0,Unprovoked,BAHAMAS,Exuma Islands,Compass Cay,Cleaning fish,male,M,...,N,16h45,Nurse shark,"Tribune 242, 7/28/2013",2013.07.28.b-Bahamas.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2013.07.28.b,2013.07.28.b,5654.0
952,2011.01.26,26-Jan-2011,2011.0,Unprovoked,BAHAMAS,West End,Tiger Beach,Scuba diving,Jim Abernethy,M,...,N,15h00,Caribbean reef shark,J. Abernethy,2011.01.26-Abernethy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2011.01.26,2011.01.26,5351.0
1287,2008.02.24,24-Feb-2008,2008.0,Unprovoked,BAHAMAS,Northern Bahamas,"Dive site known as ""The End of the Map""",Diving,Markus Groh,M,...,Y,10h00,"A bull shark, according to some of the divers ...","Sun-Sentinel, 2/25/2008",2008.02.24-Groh.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.02.24,2008.02.24,5016.0
1323,2007.09.28,28-Sep-2007,2007.0,Unprovoked,BAHAMAS,Grand Bahama Island,Sweetings Cay,Spearfishing,Leslie Gano,F,...,N,12h00,Caribbean reef shark,"A. Brenneka, SharkAttackSurvivors.com",2007.09.28-Gano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2007.09.28,2007.09.28,4980.0
1363,2007.07.10,10-Jul-2007,2007.0,Unprovoked,BAHAMAS,Abaco Islands,Allan-Pensacola Cay,Spearfishing,Joanie Regan,F,...,N,11h00,"Bull shark, 5'",J. Regan,2007.07.10-Regan.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2007.07.10,2007.07.10,4940.0
1673,2004.05.18,18-May-2004,2004.0,Provoked,BAHAMAS,Abaco Islands,Green Turtle Cay,Free diving & spearfishing,Wolfgang Leander,M,...,N,15h00,"1,5 m [5'] Caribbean reef shark (Carcharhinus ...","W. Leander, M. Levine, GSAF",2004.05.18-Leander.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2004.05.18,2004.05.18,4630.0
1756,2003.07.09,10-Jul-2003,2003.0,Unprovoked,BAHAMAS,Abaco Islands,Bakers Bay,Spearfishing,Richard Horton,M,...,N,14h30,Unidentified species,"M. Levine, GSAF; Associated Press, 7/12/03",2003.07.09-Horton.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2003.07.09,2003.07.09,4547.0
1759,2003.07.04,04-Jul-2003,2003.0,Unprovoked,BAHAMAS,Abaco Islands,10 miles west of Walker’s Cay,Spearfishing,Benjamin Brown,M,...,N,14h45,2.1 m [7'] bull shark,"Associated Press, 7/12/03; Palm Beach Post, 7/...",2003.07.04-BenBrown.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2003.07.04,2003.07.04,4544.0
1870,2002.04.09,09-Apr-2002,2002.0,Unprovoked,BAHAMAS,Abaco Islands,Walkers Cay,Standing,Erich Ritter,M,...,N,10h45,"Bull shark, 400-lb","E. Ritter, GSAF",2002.04.09-Ritter.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2002.04.09,2002.04.09,4433.0
1911,2001.08.31,31-Aug-2001,2001.0,Unprovoked,BAHAMAS,Abaco Islands,North of Grand Cay,Spearfishing,Nick Raich,M,...,N,13h30,3 m [10'] bull shark,G. Atkinson,2001.08.31-Raich.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2001.08.31,2001.08.31,4392.0
1924,2001.08.16,16-Aug-2001,2001.0,Unprovoked,BAHAMAS,Grand Bahama Island,"High Rock, 25 to 30 miles east of Freeport",Spearfishing,Kent Bonde,M,...,N,16h00,1.9 m [6.5'] bull shark,"E. Ritter, GSAF; 8/17/2001, p.A9",2001.08.16-Bonde.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2001.08.16,2001.08.16,4379.0
2111,1999.08.05,05-Aug-1999,1999.0,Unprovoked,BAHAMAS,Abaco Islands,Grand Cay,Spearfishing & holding catch,Kevin King,M,...,N,17h00,2.7 m [9'] bull shark or Caribbean reef shark,"South Florida Sun-Sentinel, 8/7/1999, p.1A; Pa...",1999.08.05-KevinKing.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1999.08.05,1999.08.05,4192.0
2171,1998.08.15,15-Aug-1998,1998.0,Unprovoked,BAHAMAS,Berry Islands,Ambergris Cay,Spearfishing,Kevin Paffrath,M,...,N,16h30,"Caribbean reef shark, 1.2 m to 1.5 m [4' to 5']","E. Ritter, GSAF",1998.08.15-Paffrath.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1998.08.15,1998.08.15,4132.0
2432,1994.06.24,24-Jun-1994,1994.0,Unprovoked,BAHAMAS,Grand Bahama Island,Freeport,Spearfishing,Alton Curtis,M,...,N,15h30,1.8 m [6'] shark,"Miami Herald, 7/9/1994",1994.06.24-Curtis.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1994.06.24,1994.06.24,3871.0
2477,1993.08.21,21-Aug-1993,1993.0,Unprovoked,BAHAMAS,Walkers Cay,"Matinella Reef, 15 to 20 miles west of Walkers...",Spearfishing,William Barnes,M,...,N,17h15,1.8 m [6'] blacktip shark or Caribbean reef shark,"South Florida Sun Sentinel, 8/22/1993, p. 1A;...",1993.08.21-Barnes.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1993.08.21,1993.08.21,3826.0
3019,1981.08.07,07-Aug-1981,1981.0,Unprovoked,BAHAMAS,Grand Bahama Island,"Gingerbread Reef, east of Little Isaac Island",Snorkeling on surface,Robert Marx,M,...,N,12h00,Mako shark (tooth fragments recovered),"R. Marx, E. Clark; M. Levine, GSAF; Note: Marx...",1981.08.07-Marx.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1981.08.07,1981.08.07,3284.0
3294,1973.09.14,14-Sep-1973,1973.0,Unprovoked,BAHAMAS,Grand Bahama Island,"Memory Rock, 18 miles from NW end of the Island","Free diving, Spearfishing",Kevin G. Schlusemeyer,M,...,N,14h30,7' to 8' bull shark,"M.Vorenberg, GSAF",1973.09.14-Schlusemeyer.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1973.09.14,1973.09.14,3009.0
3519,1967.08.00.b,Aug-1967,1967.0,Unprovoked,BAHAMAS,Out Islands,Andros Island,Photographing sharks underwater using Scuba,Richard Winer,M,...,N,Early afternoon,1.5 m to 1.8 m [5' to 6'] sandbar shark,"H.D. Baldridge, p.185",1967.08.00.b-Winer.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1967.08.00.b,1967.08.00.b,2784.0
4141,1958.09.06,06-Sep-1958,1958.0,Unprovoked,BAHAMAS,Cat Cay,off yacht Serenade,Fishing,James Douglas Munn,M,...,N,Morning,200-lb shark,"Miami Herald, 9/6/1958",1958.09.06-Munn.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1958.09.06,1958.09.06,2162.0
4154,1958.07.00.b,Jul-1958,1958.0,Unprovoked,BAHAMAS,Abaco Islands,North of Walkers Cay,"Spearfishing, had fish on his spear",Stanton Waterman,M,...,N,12h00,"Tiger shark, <2 m TL","S. Waterman, GSAF",1958.07.00.b-Waterman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1958.07.00.b,1958.07.00.b,2149.0
4725,1942.00.00.f,1942,1942.0,Unprovoked,BAHAMAS,Cay Sal Bank,Anchored off the largest island in the group,Swimming along side N.E.L. vessel Saluda,Herbert J. Mann,M,...,N,Late afternoon,1.2 m to 1.5 m [4' to 5'] shark,H.J. Mann,1942.00.00.f-Mann.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1942.00.00.f,1942.00.00.f,1578.0
4794,1939.07.16,16-Jul-1939,1939.0,Provoked,BAHAMAS,Andros Islands,Blue Hole,"Dress diving, filming shark & pulling it throu...",E.F. MacEwan,M,...,N,12h00,"Nurse shark, 2.1 m [7']","Evening Sun (Baltimore), 7/31/1939; E.R.F. Joh...",1939.07.16-MacEwan.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1939.07.16,1939.07.16,1509.0

In [401]:
BAHAMAS_sharks = {
    'Area':
    ['New Providence',
    'Abaco Islands',
    'Exuma Islands',
    'West End',
    'Northern Bahamas',
    'Grand Bahama Island',
    'Berry Islands',
    'Walkers Cay',
    'Out Islands',
    'Cat Cay',
    'Cay Sal Bank',
    'Andros Islands'],
    'Lat': [25.051928,
           26.467,
           23.533,
           26.68711,
           25.025885,
           26.659447,
           25.5667,
           25.083333,
           25.025885,
           25.55625,
           23.688889,
           24.433333],
    'Long': [-77.40134,
            -77.083,
            -75.833,
            -78.97702,
            -78.035889,
            -78.52065,
            -77.7500,
            -78.016667,
            -78.035889,
            -79.277139,
            -80.390556,
            -77.95]
}

In [402]:
# Creating dataframe with lat and long for BAHAMAS data 
BAHAMAS_sharks_df = pd.DataFrame(data= BAHAMAS_sharks)
BAHAMAS_sharks_df

                   Area        Lat       Long
0        New Providence  25.051928 -77.401340
1         Abaco Islands  26.467000 -77.083000
2         Exuma Islands  23.533000 -75.833000
3              West End  26.687110 -78.977020
4      Northern Bahamas  25.025885 -78.035889
5   Grand Bahama Island  26.659447 -78.520650
6         Berry Islands  25.566700 -77.750000
7           Walkers Cay  25.083333 -78.016667
8           Out Islands  25.025885 -78.035889
9               Cat Cay  25.556250 -79.277139
10         Cay Sal Bank  23.688889 -80.390556
11       Andros Islands  24.433333 -77.950000

In [406]:
# printing areas in BAHAMAS
NEWCAL_sharks = sharkAttacks_cleaned.loc[sharkAttacks['Country'] == 'NEW CALEDONIA']

In [418]:
NEW_CAL_sharks = sharkAttacks.loc[sharkAttacks['Country'] == 'NEW CALEDONIA'].Area.unique()
NEW_CAL_sharks

array([nan, 'North Province', 'Grand Terre', 'South Province',
       'Baie de Sainte-Marie', ' Loyalty Islands', 'Loyalty Islands'],
      dtype=object)

In [410]:
NEWCAL_sharks.replace([' Loyalty Islands'], 'Loyalty Islands')

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
288,2016.04.09,09-Apr-2016,2016.0,Unprovoked,NEW CALEDONIA,Grand Terre,Poe Beach,Walking,Nicole Malignon,F,...,Y,10h45,"Tiger shark, 2.5 m",Les Nouvelles Caledonnie. 4/11/2016,2016.04.09-Malignon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.04.09,2016.04.09,6015.0
590,2013.12.25,25-Dec-2013,2013.0,Unprovoked,NEW CALEDONIA,North Province,"Lindéralique, Hienghène",Snorkeling,Loïc Merlet,M,...,N,11h00,Reported to involve a bull shark,"Les Novelles Caledonie, 12/26/2014",2013.12.25-NewCaledonia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2013.12.25,2013.12.25,5713.0
923,2011.05.21.a,21-May-2011,2011.0,Unprovoked,NEW CALEDONIA,North Province,Kendec,Kite Boarding,Nathan ____,M,...,Y,11h00,"Tiger shark, 2.8m",Radio New Zealand & Les Nouvelles Caledonienne...,2011.05.21.a-Nathan.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2011.05.21.a,2011.05.21.a,5380.0
943,2011.02.23,23-Feb-2011,2011.0,Unprovoked,NEW CALEDONIA,Loyalty Islands,"Bay of Bweedro, Ouvéa",Spearfishing,Jean-Luc Majele,M,...,N,Early afternoon,1.5 m shark,"Les Nouvelles Caledoniennes, 2/25/2011",2011.02.23-Jean-Luc.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2011.02.23,2011.02.23,5360.0
1260,2008.05.07.b,07-May-2008,2008.0,Unprovoked,NEW CALEDONIA,North Province,Hienghène,Fishing,male,M,...,N,14h00,2 small bull sharks,"C. Johansson, GSAF",2008.05.07.b-NewCaledonia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.05.07.b,2008.05.07.b,5043.0
1266,2008.04.26.b,26-Apr-2008,2008.0,Unprovoked,NEW CALEDONIA,North Province,Poindimié,Swimming,Olivier Vilain,M,...,N,Morning,"Bull shark, 1.8m","Les Nouvelles Calédonie, 4/28/2008 & 4/29/2008",2008.04.26.b-Vilain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.04.26.b,2008.04.26.b,5037.0
1322,2007.09.30.a,30-Sep-2007,2007.0,Unprovoked,NEW CALEDONIA,Loyalty Islands,"Bay of Luengoni, Lifou Island",Swimming,Stéphanie Belliard,F,...,Y,Early morning,Tiger shark,"Les Nouvelles Caledoniennes, 10/1/2007",2007.09.30.a-Belliard.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2007.09.30.a,2007.09.30.a,4981.0
1390,2007.04.09,09-Apr-2007,2007.0,Unprovoked,NEW CALEDONIA,South Province,Dumbéa,Surfing,Olivier Bertholom,M,...,N,16h00,Tiger shark,"Les Nouvelles Calédoniennes, 4/11/2007",2007.04.09-Bertholom.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2007.04.09,2007.04.09,4913.0
1404,2007.01.25.b,25-Jan-2007,2007.0,Unprovoked,NEW CALEDONIA,North Province,Kaala-Gomen,Spearfishing (free diving),Jesse Jizdny,M,...,N,14h00,Tiger shark,"Les Nouvelles Caledoniennes, 1/29/2007",2007.01.25.b-Jizdny.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2007.01.25.b,2007.01.25.b,4899.0
2064,2000.03.15,15-Mar-2000,2000.0,Unprovoked,NEW CALEDONIA,North Province,Poum,Spearfishing,Gilbert Bui Van Minh,M,...,Y,Morning,Tiger shark?,"Les Nouvelles Caledoniennes, 3/16/2000",2000.03.15-GilbertBui.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.03.15,2000.03.15,4239.0

In [411]:
N_CALEDONIA_sharks = {
    'Area':
    ['Grand Terre',
    'North Province',
    'Loyalty Islands',
    'South Province'],
    'Lat': [-21.283333,
            -21,
            -21.066667,
            -21.916667],
    'Long': [165.35,
             165,
             167.35,
             166.333333]
}

In [413]:
# Creating dataframe with lat and long for NEW CALEDONIA data 
N_CALEDONIA_df = pd.DataFrame(data= N_CALEDONIA_sharks)
N_CALEDONIA_df

              Area        Lat        Long
0      Grand Terre -21.283333  165.350000
1   North Province -21.000000  165.000000
2  Loyalty Islands -21.066667  167.350000
3   South Province -21.916667  166.333333

In [ ]:
, 'NEW CALEDONIA',
       'ECUADOR', 'MALAYSIA', 'LIBYA', nan, 'CUBA', 'MAURITIUS',
       'NEW ZEALAND', 'SPAIN', 'SAMOA', 'SOLOMON ISLANDS', 'JAPAN',
       'EGYPT', 'ST HELENA, British overseas territory', 'COMOROS',
       'REUNION', 'FRENCH POLYNESIA', 'UNITED KINGDOM',
       'UNITED ARAB EMIRATES', 'PHILIPPINES', 'INDONESIA', 'CHINA',
       'COLUMBIA', 'CAPE VERDE', 'Fiji', 'DOMINICAN REPUBLIC'