In [1]:
import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
shark_attack = pd.read_csv('sharkattack.csv')
shark_attack = shark_attack.drop(columns=['Unnamed: 8', 'Unnamed: 9'])
shark_attack = shark_attack.dropna()
shark_attack.to_csv('firstclean.csv')
shark_attack.head()

,Area,Activity,Sex,Age,Injury,Fatal (Y/N),Time,Species
0,California,Paddling,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark
6,Pernambuco,Swimming,M,18,FATAL,Y,Late afternoon,Tiger shark
8,Florida,Walking,M,15,Lower left leg bitten,N,17h00,"Bull shark, 6'"
10,Queensland,Feeding sharks,M,32,Minor bite to hand by captive shark. PROVOKED ...,N,Morning,Grey reef shark
13,Cornwall,Fishing,M,21,Injured by teeth of a dead porbeagle shark he ...,N,08h15,Invalid incident

In [3]:
#unique_area = shark_attack['Area'].unique()
#unique_country = shark_attack['Country'].unique()
#unique_area_df = pd.DataFrame(unique_area)
#unique_country_df = pd.DataFrame(unique_country)
#unique_area_df.to_csv('Unique_Area.csv')
#unique_country_df.to_csv('Unique_Country.csv')

In [26]:
test1 = pd.read_csv('second_clean.csv')
test1.info()
test1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1435 entries, 0 to 1434
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Area        1435 non-null   object
 1   Activity    1435 non-null   object
 2   Sex         1435 non-null   object
 3   Age         1435 non-null   int64
 4   Injury      1435 non-null   object
 5   Fatal(Y/N)  1435 non-null   object
 6   Time        1435 non-null   object
 7   Species     1435 non-null   object
dtypes: int64(1), object(7)
memory usage: 89.8+ KB

,Area,Activity,Sex,Age,Injury,Fatal(Y/N),Time,Species
0,California,Paddling,F,57,Non_Fatal,N,Evening,White shark
1,Pernambuco,Swimming,M,18,FATAL,Y,Evening,Tiger shark
2,Florida,Walking,M,15,Non_Fatal,N,Evening,"Bull shark, 6'"
3,Queensland,Feeding sharks,M,32,Non_Fatal,N,Morning,Grey reef shark
4,Cornwall,Fishing,M,21,Non_Fatal,N,Morning,Invalid incident
...,...,...,...,...,...,...,...,...
1430,Hoogly River,Standing,M,35,FATAL,Y,Morning,Identified as C. gangeticus by Dr. J. Fayrer
1431,Florida,Shark tagging,F,21,Non_Fatal,N,Evening,"Blacktip shark, 5'"
1432,Basrah,Swimming naked near a date palm where many dat...,M,6,Non_Fatal,N,Afternoon,Bull shark
1433,Basrah,Swimming in section of river used for washing ...,M,16,Non_Fatal,N,Afternoon,Bull shark
1434,Basrah,Swimming,M,13,FATAL,Y,Afternoon,Bull shark

In [27]:
X = test1.drop(labels='Fatal(Y/N)', axis=1)
#X = np.array(X)
#print(X)
    
#     define label
y = test1['Fatal(Y/N)']

In [24]:
from sklearn.model_selection import train_test_split
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=1)

#from sklearn.linear_model import LogisticRegression
#classifier = LogisticRegression()

from sklearn.ensemble import RandomForestClassifier
classifier = LogisticRegression()

classifier.fit(X_train, y_train)

print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

predictions = classifier.predict(X_test)
print(f"First 10 Predictions:   {predictions[:10]}")
print(f"First 10 Actual labels: {y_test[:10].tolist()}")

pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)

ValueError: could not convert string to float: 'Malampa Province'